In [2]:
from urllib.request import urlopen
from bs4 import BeautifulSoup

import re
import pandas as pd
from datetime import datetime, timedelta

In [21]:
# https://search.shopping.naver.com/best100v2/detail.nhn?catId=50000190

category_df = pd.DataFrame({
    'category' : ['스킨케어', '베이스메이크업', '색조메이크업', '클렌징', 
                  '마스크/팩', '선케어', '남성화장품', '향수', 
                  '바디케어', '헤어케어', '헤어스타일링', '네일케어',
                 '뷰티소품'],
    'category_code' : ['50000190', '50000194', '50000195', '50000192', 
                       '50000193','50000191', '50000202', '50000200',
                      '50000197', '50000198', '50000199', '50000196',
                      '50000201']
})

total = pd.DataFrame()

today_dt = datetime.today()

for catid in range(len(category_df)):
    category_nm = category_df['category'][catid]
    category_code = category_df['category_code'][catid]

    url = 'https://search.shopping.naver.com/best100v2/detail.nhn?catId=' + category_code
    
    
    html = urlopen(url)
    bsObject = BeautifulSoup(html, "html.parser")

    tag = 'li'
    className = '_itemSection'
    content = bsObject.body.find_all(tag,{"class", className})


    # for i in range(3):
    for i in range(len(content)):
        tag = "p"
        className = "cont"
        title = content[i].find(tag,{"class", className})
        title_name = title.text.replace('\n',"")

        tag = "div"
        className = "price"
        price = content[i].find(tag,{"class", className})
        price_name = price.text.replace('\n','')
        
        price_num = numbers = re.sub(r'[^0-9]', '', price_name)
        
        df = pd.DataFrame({
            'date' : [today_dt],
            'category' : [category_nm],
            'title' : [title_name],
            'price' : [price_num],
        })
        total = pd.concat([total, df])

# 저장
# total.to_csv("top_100.csv", index = False)

# # .to_csv 
# # 최초 생성 이후 mode는 append
# if not os.path.exists('top_100.csv'):
#     df.to_csv('top_100.csv', index=False, mode='w')
# else:
#     df.to_csv('top_100.csv', index=False, mode='a', header=False)

In [22]:
total

                         date category                         title  price
0  2021-08-06 01:01:32.586299     스킨케어           가히 링클 바운스 멀티밤 스틱 9g  24220
0  2021-08-06 01:01:32.586299     스킨케어  AHC 유스래스팅 리얼 아이크림 포페이스 30...   2000
0  2021-08-06 01:01:32.586299     스킨케어     강블리 알로에 베라 모이스처 에멀전 150ml   2000
0  2021-08-06 01:01:32.586299     스킨케어                  설화수 자음 2종 세트  56380
0  2021-08-06 01:01:32.586299     스킨케어   닥터지 레드 블레미쉬 클리어 수딩 크림 70...  12230
..                        ...      ...                           ...    ...
0  2021-08-06 01:01:32.586299     뷰티소품               코지트 해피 페이스 트레이너   2000
0  2021-08-06 01:01:32.586299     뷰티소품               엘프 브러쉬 앤 퍼프 클렌저   7420
0  2021-08-06 01:01:32.586299     뷰티소품         피카소 블랙 머쉬멜로우 메이크업 스펀지   9400
0  2021-08-06 01:01:32.586299     뷰티소품           블랑두 스킨 토너 팩 1/2 화장솜   1500
0  2021-08-06 01:01:32.586299     뷰티소품              필리밀리 빅 팬 브러시 851  11990

[1300 rows x 4 columns]

In [3]:
category_df = pd.DataFrame({
    'category' : ['스킨케어', '베이스메이크업', '색조메이크업', '클렌징', 
                  '마스크/팩', '선케어', '남성화장품', '향수', 
                  '바디케어', '헤어케어', '헤어스타일링', '네일케어',
                 '뷰티소품'],
    'category_code' : ['50000190', '50000194', '50000195', '50000192', 
                       '50000193','50000191', '50000202', '50000200',
                      '50000197', '50000198', '50000199', '50000196',
                      '50000201']
})

total = pd.DataFrame()

today_dt = datetime.today()

### url code
url code setting

In [4]:
category_df

   category category_code
0      스킨케어      50000190
1   베이스메이크업      50000194
2    색조메이크업      50000195
3       클렌징      50000192
4     마스크/팩      50000193
5       선케어      50000191
6     남성화장품      50000202
7        향수      50000200
8      바디케어      50000197
9      헤어케어      50000198
10   헤어스타일링      50000199
11     네일케어      50000196
12     뷰티소품      50000201

### url 생성

url code와 함께 url 생성

In [5]:
catid = 0
category_nm = category_df['category'][catid]
category_code = category_df['category_code'][catid]

url = 'https://search.shopping.naver.com/best100v2/detail.nhn?catId=' + category_code

### url 파싱

In [7]:
html = urlopen(url)
bsObject = BeautifulSoup(html, "html.parser")

### 태그 파싱

li 테그와, _itemSection 명을 찾아서 수집

In [9]:
tag = 'li'
className = '_itemSection'

content = bsObject.body.find_all(tag,{"class", className})

### Title

In [13]:
i = 0

In [16]:
tag = "p"
className = "cont"
title = content[i].find(tag,{"class", className})
title_name = title.text.replace('\n',"")

title_name

'가히 링클 바운스 멀티밤 스틱 9g'

### Price

In [18]:
tag = "div"
className = "price"
price = content[i].find(tag,{"class", className})
price_name = price.text.replace('\n','')
        
price_num = re.sub(r'[^0-9]', '', price_name)
price_num

'24220'

In [19]:
for i in range(len(content)):
        tag = "p"
        className = "cont"
        title = content[i].find(tag,{"class", className})
        title_name = title.text.replace('\n',"")

        tag = "div"
        className = "price"
        price = content[i].find(tag,{"class", className})
        price_name = price.text.replace('\n','')
        
        price_num = numbers = re.sub(r'[^0-9]', '', price_name)
        
        df = pd.DataFrame({
            'date' : [today_dt],
            'category' : [category_nm],
            'title' : [title_name],
            'price' : [price_num],
        })
        total = pd.concat([total, df])

In [20]:
total

                         date category                          title  price
0  2021-08-06 00:53:41.070589     스킨케어            가히 링클 바운스 멀티밤 스틱 9g  24220
0  2021-08-06 00:53:41.070589     스킨케어   AHC 유스래스팅 리얼 아이크림 포페이스 30...   2000
0  2021-08-06 00:53:41.070589     스킨케어      강블리 알로에 베라 모이스처 에멀전 150ml   2000
0  2021-08-06 00:53:41.070589     스킨케어                   설화수 자음 2종 세트  56380
0  2021-08-06 00:53:41.070589     스킨케어    닥터지 레드 블레미쉬 클리어 수딩 크림 70...  12230
..                        ...      ...                            ...    ...
0  2021-08-06 00:53:41.070589     스킨케어               제로이드 수딩 로션 200ml  29640
0  2021-08-06 00:53:41.070589     스킨케어  MISSHA 타임 레볼루션 나이트 리페어 보랏빛...  17390
0  2021-08-06 00:53:41.070589     스킨케어          마몽드 세라마이드 인텐스 크림 50ml  13310
0  2021-08-06 00:53:41.070589     스킨케어                설화수 자음 유액 125ml  33000
0  2021-08-06 00:53:41.070589     스킨케어        아이오페 바이오 컨디셔닝 에센스 168ml  30190

[100 rows x 4 columns]